### ISSUE TITLE
Please cut 0.10

### ISSUE THREAD

**Issue by GrayTShirt** [salortiz/LMDB_File#15]
with the stabilization of 5.24 this bug fix should probably be deployed: https://github.com/salortiz/LMDB_File/commit/3f3858dd62d20f95935ab64245f032471936a92f

**Comment by salortiz** [comment]
@GrayTShirt Any moment you'll see v0.10 in you preferred CPAN mirror.

**Comment by GrayTShirt** [comment]
Awesome thanks! It's working with 5.24.
