### ISSUE TITLE
Broken test t/01-environment.t

### ISSUE THREAD

**Issue by rouzier** [salortiz/LMDB_File#4]
In linux kernels where fdatasync is broken the 'Flags setted' test in 01-environment.t will fail.
This is because there is an additional private flag set 'MDB_FSYNCONLY'  not just MDB_ENV_ACTIVE | MDB_ENV_TXKEY.

**Comment by salortiz** [comment]
With a recent liblmdb (0.9.16+) OR the latest LMDB_File (post 0.08) all problems with leaked private flags should be solved.

Fell free to reopen the issue if not de case.
